### ISSUE TITLE
Add link to self-service page (didmos2 frontend)

### ISSUE THREAD

**Issue by darh** [crusttech/webapp-unify#14]

**Comment by lenny-horstink** [comment]
Just would like to add that the link on the icon of the user opens the self service portal in a new window.

![image](https://user-images.githubusercontent.com/44468809/53797273-2438d900-3f36-11e9-9c3e-9e7b1902b3a0.png)

However, the "Back to Crust", simply opens Crust (instead of closing the browser tab)

![image](https://user-images.githubusercontent.com/44468809/53797416-6c57fb80-3f36-11e9-8d1d-7dc2dbda4fda.png)

So, you end up with two browser tabs with Crust.

Maybe the link on the icon of the user should not open in a new browser tab?
